version: "3.9"

services:
  api:
    # container_name: api
    build: .
    # ports:
    #   - 3000:3000
  nginx:
    image: nginx:latest
    volumes:
      - ./conf.d:/etc/nginx/conf.d
    depends_on:
      - serviceName: api
    ports:
      - 3000:3000
